module.exports = {
  INVALID_REQUEST: 'Ошибочный запрос',
  NOT_FOUND: 'Запрашиваемый ресурс не найден',
  ITEM_NOT_FOUND: 'Не существует',
  INVALID_LINK: 'Неверный формат',
  BAD_REQUEST: 'Некорректный запрос',
  SERVER_ERROR: 'На сервере произошла ошибка',
  AUTH: 'Доступ запрещен. Необходима авторизация',
  ERROR_EMAIL_PASS: 'Неправильные почта или пароль',
  EMPTY_DATABASE: 'База данных статей пуста!',
  NOT_YOUR_ARTICLE: 'Это не ваша статья',
  ARTICLE_NOT_FOUND: 'Статья не найдена',
  UNABLE_TO_CREATE_ARTICLE: 'Не удается создать статью',
  FAILED_CREATE_USER: 'Не удалось создать пользователя',
};
